services:
  database:
    image: postgres:15
    container_name: app_postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: securepass123
      POSTGRES_DB: application_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7
    container_name: app_redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass securepass123 --appendonly yes
    environment:
      - REDIS_PASSWORD=securepass123
    volumes:
      - redis_cache:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  redis_cache: